site_name: AI-Open-Science documentation
nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Tests: rationale.md
theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true